tasks:
  - name: install-dependencies
    init: |
      docker pull cassandra:4
      pip install -U cqlsh
    command: | 
      docker run -d --name casya --publish 9042:9042 cassandra:4
      timeout 60 bash -c 'until cqlsh -e "describe cluster" >/dev/null 2>&1; do sleep 2; done';
ports:
  - port: 9042
    onOpen: ignore  
github:
  prebuilds:
    main: true
vscode:
  extensions:
    - hadesarchitect.katapod@1.0.0
