tasks:
  - name: install-cqlsh
    init: |
      pip install -U cqlsh
  - name: install-cassandra
    init: |
      docker pull cassandra:4
    command: | 
      echo "Wait for Cassandra to start..."
      docker run -p 9042:9042 -d cassandra:4
      gp await-port 9042
      echo "Ready, let's roll!"
ports:
  - port: 9042
    onOpen: ignore  
github:
  prebuilds:
    main: true
vscode:
  extensions:
    - https://github.com/HadesArchitect/katapod/releases/download/0.3.2/katapod-0.3.2.vsix
