tasks:
  - name: install-dependencies
    init: |
      docker pull cassandra:4
      pip install -U cqlsh
      docker run -d --name casya --volume casya:/var/lib/cassandra cassandra:4
      until cqlsh -e "describe cluster" >/dev/null 2>&1; do sleep 2; done
      docker stop casya
    command: | 
      docker run -p 9042:9042 -d --volume casya:/var/lib/cassandra cassandra:4
      timeout 60 bash -c 'until cqlsh -e "describe cluster" >/dev/null 2>&1; do sleep 2; done';
ports:
  - port: 9042
    onOpen: ignore  
github:
  prebuilds:
    main: true
vscode:
  extensions:
    - https://github.com/HadesArchitect/katapod/releases/download/0.3.6/katapod-0.3.6.vsix
